# These are supported funding model platforms

github:
patreon:
ko_fi:
tidelift:
community_bridge:
liberapay: Aventra_Technology
open_collective:
issuehunt:
otechie:

custom:
  - "https://aventra.technology/donate"
