version: 1.1.30
files:
  - url: Flux.Tasks.Setup.exe
    sha512: 9vwA25X7+7yr2Ve7MnJy8Y7QyHx2oFZ7kakDdPr93g7QOcRHBQhzewcv8ECaw6LV4f8whrQa0DzNdoD26liqaQ==
    size: 119365653
path: Flux.Tasks.Setup.exe
sha512: 9vwA25X7+7yr2Ve7MnJy8Y7QyHx2oFZ7kakDdPr93g7QOcRHBQhzewcv8ECaw6LV4f8whrQa0DzNdoD26liqaQ==
releaseDate: '2026-07-09T17:21:45.687Z'
