version: 1.1.29
files:
  - url: Flux.Tasks.Setup.exe
    sha512: /7BCAss3irzZJ79H/C8WVdPFTkz2GTZQaawXSLjT1jPYiVh+S6C1VhLYQNNaetQFYiMCLZYK2mrsNFvwLTNA2w==
    size: 119365602
path: Flux.Tasks.Setup.exe
sha512: /7BCAss3irzZJ79H/C8WVdPFTkz2GTZQaawXSLjT1jPYiVh+S6C1VhLYQNNaetQFYiMCLZYK2mrsNFvwLTNA2w==
releaseDate: '2026-07-10T10:45:11.105Z'
